### PR TITLE
use new JLL

### LINKED ISSUE #29: Error when `using SDPAFamily`
Sometimes I get this error when calling `using SDPAFamily`:
```
ERROR: could not load library "/Applications/Julia-1.3.app/Contents/Resources/julia/lib/julia/sys.dylib"
dlopen(/Applications/Julia-1.3.app/Contents/Resources/julia/lib/julia/sys.dylib, 6): Symbol not found: _jl_apply_2va
  Referenced from: /Applications/Julia-1.0.app/Contents/Resources/julia/lib/julia/sys.dylib
  Expected in: /Applications/Julia-1.3.app/Contents/Resources/julia/bin/../lib/libjulia.dylib
 in /Applications/Julia-1.0.app/Contents/Resources/julia/lib/julia/sys.dylib
```
I think it comes from using SDPAFamily from different Julia versions, and needing to rebuild the package. I'm not quite sure how to fix it; I think one easy fix might just be to remove the plain-SDPA functionality and only support the high-precision variants, since then we don't need to link against anything.

### PR DESCRIPTION
**Pull request by ericphanson**
closes #29

I saw some strange failures locally (the binary not writing the output file?) so let's see what CI sees.

### CODE REVIEW

**Comment by ViralBShah** [comment]
@giordano @staticfloat  - Any idea why these are failing on mac? We were unable to do the libgfortran expnsion because of libcxxwrap - so is there any way forward?

**Comment by giordano** [comment]
How come libgfortran can't be found? :confused:

**Comment by giordano** [comment]
@ericphanson can you please run
```julia
using Libdl
filter!(lib -> occursin("fortran", lib), dllist())
```
at the beginning of the tests?

**Comment by ViralBShah** [comment]
I guess that would suggest that `SDPA_jll` was not built correctly.

**Comment by ViralBShah** [comment]
@ericphanson Bump to try @giordano's suggestion.

**Comment by ericphanson** [comment]
Thanks for the reminder, done!

**Comment by ericphanson** [comment]
Results:

-  Julia 1.4: `[ Info: ["/Users/runner/hostedtoolcache/julia/1.4.2/x64/lib/julia/libgfortran.5.dylib"]` (https://github.com/ericphanson/SDPAFamily.jl/runs/1053047244?check_suite_focus=true#step:5:79)
-  1.5.1: `[ Info: ["/Users/runner/hostedtoolcache/julia/1.5.1/x64/lib/julia/libgfortran.4.dylib", "/Users/runner/.julia/artifacts/81503c38a478022b7c49f58334fbe900bbf7a68d/lib/libgfortran.4.dylib"] ` (https://github.com/ericphanson/SDPAFamily.jl/runs/1053047275?check_suite_focus=true#step:5:95)
-  Nightly: `["/Users/runner/hostedtoolcache/julia/nightly/x64/lib/julia/libgfortran.4.dylib", "/Users/runner/.julia/artifacts/81503c38a478022b7c49f58334fbe900bbf7a68d/lib/libgfortran.4.dylib"] ` (https://github.com/ericphanson/SDPAFamily.jl/runs/1053047309?check_suite_focus=true#step:5:95)

**Comment by giordano** [comment]
It looks like julia v1.4 on macos comes with libgfortran 5?!? For the other platforms, as far as I can see on the phone the library is loaded correctly but accuracy tests are failing?

**Comment by ericphanson** [comment]
Good point, I hadn’t scrolled down to check the failures. We can just relax the tolerances for those. If it’s only a 1.4 issue then we could just drop support at some point.

**Comment by giordano** [comment]
Honestly I'm surprised julia v1.4 on macos uses a different libgfortran (v5) than the other platforms and versions of Julia on the same platform (all of them v4). @staticfloat is that correct?

**Comment by staticfloat** [comment]
Unfortunately, yes.  We're constrained by the gfortran support that we get via Homebrew, and there was some problem with GCC@7 a while back so we just upgraded the buildbots to GCC@9.

**Comment by ViralBShah** [comment]
Fun

**Comment by ViralBShah** [comment]
Is this something we should open an issue for? Or simply just use Julia 1.5 as a minimum and move on for now?

**Comment by ViralBShah** [comment]
Can we update this PR to be 1.5 only and see if it works out?

**Comment by ericphanson** [comment]
Seems to work on 1.5! I am seeing weird failures locally on WSL2 about temp directories SDPAFamily creates not being found (possibly related to https://github.com/JuliaLang/julia/issues/37029? not sure, I need to look into it more). I see the same on master, however, so I'll merge this.

<details>
<summary> Example failure on WSL2 </summary>

```julia
geomean2f: Error During Test at /home/eric/.julia/packages/MathOptInterface/bygN7/src/Test/config.jl:47
  Got exception outside of a @test
  SystemError: opening file "/tmp/jl_D02HKQ/output.dat": No such file or directory
  Stacktrace:
   [1] systemerror(::String, ::Int32; extrainfo::Nothing) at ./error.jl:168
   [2] #systemerror#48 at ./error.jl:167 [inlined]
   [3] systemerror at ./error.jl:167 [inlined]
   [4] open(::String; lock::Bool, read::Bool, write::Nothing, create::Nothing, truncate::Nothing, append::Nothing) at ./iostream.jl:284
   [5] open(::String, ::String; lock::Bool) at ./iostream.jl:346
   [6] open(::String, ::String) at ./iostream.jl:346
   [7] open(::SDPAFamily.var"#23#29"{Float64,SDPAFamily.Optimizer{Float64},SDPAFamily.var"#getnextline#26"{String},SDPAFamily.var"#remove_brackets!#28",Array{Float64,1},Array{Float64,1}}, ::String, ::Vararg{String,N} where N; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at ./io.jl:323
   [8] open at ./io.jl:323 [inlined]
   [9] read_results!(::SDPAFamily.Optimizer{Float64}, ::String, ::Array{Int64,1}) at /mnt/c/Users/eric/Code/SDPAFamily.jl/src/file_io.jl:39
   [10] sdpa_gmp_binary_solve!(::SDPAFamily.Optimizer{Float64}, ::String, ::String; redundant_entries::Array{Int64,1}) at /mnt/c/Users/eric/Code/SDPAFamily.jl/src/binary_call.jl:58
   [11] optimize!(::SDPAFamily.Optimizer{Float64}) at /mnt/c/Users/eric/Code/SDPAFamily.jl/src/MOI_wrapper.jl:346
   [12] optimize!(::MathOptInterface.Utilities.CachingOptimizer{SDPAFamily.Optimizer{Float64},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}) at /home/eric/.julia/packages/MathOptInterface/bygN7/src/Utilities/cachingoptimizer.jl:189
   [13] optimize! at /home/eric/.julia/packages/MathOptInterface/bygN7/src/Bridges/bridge_optimizer.jl:239 [inlined]
   [14] _geomean2test(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{SDPAFamily.Optimizer{Float64},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, ::MathOptInterface.Test.TestConfig{Float64}, ::Bool) at /home/eric/.julia/packages/MathOptInterface/bygN7/src/Test/contconic.jl:1462
   [15] geomean2ftest(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{SDPAFamily.Optimizer{Float64},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, ::MathOptInterface.Test.TestConfig{Float64}) at /home/eric/.julia/packages/MathOptInterface/bygN7/src/Test/contconic.jl:1478
   [16] macro expansion at /home/eric/.julia/packages/MathOptInterface/bygN7/src/Test/config.jl:48 [inlined]
   [17] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1115 [inlined]
   [18] geomeantest(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{SDPAFamily.Optimizer{Float64},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, ::MathOptInterface.Test.TestConfig{Float64}, ::Array{String,1}) at /home/eric/.julia/packages/MathOptInterface/bygN7/src/Test/config.jl:48
   [19] macro expansion at /home/eric/.julia/packages/MathOptInterface/bygN7/src/Test/config.jl:48 [inlined]
   [20] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1115 [inlined]
   [21] contconictest(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{SDPAFamily.Optimizer{Float64},MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, ::MathOptInterface.Test.TestConfig{Float64}, ::Array{String,1}) at /home/eric/.julia/packages/MathOptInterface/bygN7/src/Test/config.jl:48
   [22] macro expansion at /mnt/c/Users/eric/Code/SDPAFamily.jl/test/MOI_wrapper.jl:68 [inlined]
   [23] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1115 [inlined]
   [24] macro expansion at /mnt/c/Users/eric/Code/SDPAFamily.jl/test/MOI_wrapper.jl:68 [inlined]
   [25] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1190 [inlined]
   [26] macro expansion at /mnt/c/Users/eric/Code/SDPAFamily.jl/test/MOI_wrapper.jl:12 [inlined]
   [27] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1190
   [28] include(::String) at ./client.jl:457
   [29] top-level scope at /mnt/c/Users/eric/Code/SDPAFamily.jl/test/runtests.jl:23
   [30] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Test/src/Test.jl:1115
   [31] top-level scope at /mnt/c/Users/eric/Code/SDPAFamily.jl/test/runtests.jl:13
   [32] include(::String) at ./client.jl:457
   [33] top-level scope at none:6
   [34] eval(::Module, ::Any) at ./boot.jl:331
   [35] exec_options(::Base.JLOptions) at ./client.jl:272
   [36] _start() at ./client.jl:506
```
</details>

**Pull request merged**
